# ====================================================================================
# 🏗️ Nginx Deployment with Horizontal Pod Autoscaler and ClusterIP Service
# ====================================================================================
# This configuration file sets up:
# 1. An Nginx Web server deployment with two replicas.
# 2. Horizontal Pod Autoscaler (HPA) to automatically scale based on CPU and memory.
# 3. A ClusterIP service to expose Nginx internally within the Kubernetes cluster.
# ====================================================================================

# ====================================================================================
# 1️⃣ Nginx Deployment
# ====================================================================================
# Deploys two Nginx pods (`httpd:latest`) that listen on port 80.
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 2                                         # Start with 2 Nginx replicas
  selector:
    matchLabels:
      app: nginx                                     # Selector matches pods with label 'app: Nginx'
  template:
    metadata:
      labels:
        app: nginx                                   # Labels applied to pods for service and HPA targeting
    spec:
      containers:
      - name: nginx-container
        image: nginx:latest                           # Official Nginx Server Docker image
        ports:
        - containerPort: 80                           # Expose port 80 inside the container

---
# ====================================================================================
# 2️⃣ Horizontal Pod Autoscaler (HPA)
# ====================================================================================
# Automatically scales Nginx pods based on CPU and memory utilization.
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: nginx-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: nginx-deployment                           # Target the Nginx deployment for scaling
  minReplicas: 2                                      # Minimum 2 pods running at all times
  maxReplicas: 10                                     # Maximum scaling up to 10 pods
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50                      # Scale up if average CPU usage exceeds 50%
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 50                      # Scale up if average memory usage exceeds 50%

---
# ====================================================================================
# 3️⃣ Nginx ClusterIP Service
# ====================================================================================
# Exposes the Nginx deployment internally in the cluster on port 80.
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  type: ClusterIP                                     # Default service type for internal-only access
  selector:
    app: nginx                                       # Route traffic to pods with label 'app: nginx'
  ports:
    - protocol: TCP
      port: 80                                        # Expose service on port 80
      targetPort: 80                                  # Forward traffic to pods' port 80
