# ====================================================================================
# 🏗️ Apache Deployment with Horizontal Pod Autoscaler and ClusterIP Service
# ====================================================================================
# This configuration file sets up:
# 1. An Apache HTTP server deployment with two replicas.
# 2. Horizontal Pod Autoscaler (HPA) to automatically scale based on CPU and memory.
# 3. A ClusterIP service to expose Apache internally within the Kubernetes cluster.
# ====================================================================================

# ====================================================================================
# 1️⃣ Apache Deployment
# ====================================================================================
# Deploys two Apache pods (`httpd:latest`) that listen on port 80.
apiVersion: apps/v1
kind: Deployment
metadata:
  name: apache-deployment
  labels:
    app: apache
spec:
  replicas: 2                                         # Start with 2 Apache replicas
  selector:
    matchLabels:
      app: apache                                     # Selector matches pods with label 'app: apache'
  template:
    metadata:
      labels:
        app: apache                                   # Labels applied to pods for service and HPA targeting
    spec:
      containers:
      - name: apache-container
        image: httpd:latest                           # Official Apache HTTP Server Docker image
        ports:
        - containerPort: 80                           # Expose port 80 inside the container

---
# ====================================================================================
# 2️⃣ Horizontal Pod Autoscaler (HPA)
# ====================================================================================
# Automatically scales Apache pods based on CPU and memory utilization.
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: apache-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: apache-deployment                           # Target the Apache deployment for scaling
  minReplicas: 2                                      # Minimum 2 pods running at all times
  maxReplicas: 10                                     # Maximum scaling up to 10 pods
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50                      # Scale up if average CPU usage exceeds 50%
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 50                      # Scale up if average memory usage exceeds 50%

---
# ====================================================================================
# 3️⃣ Apache ClusterIP Service
# ====================================================================================
# Exposes the Apache deployment internally in the cluster on port 80.
apiVersion: v1
kind: Service
metadata:
  name: apache-service
spec:
  type: ClusterIP                                     # Default service type for internal-only access
  selector:
    app: apache                                       # Route traffic to pods with label 'app: apache'
  ports:
    - protocol: TCP
      port: 80                                        # Expose service on port 80
      targetPort: 80                                  # Forward traffic to pods' port 80
